Repository nextcloud/app_template, pull requests merged in 2024-08, with the labels that each got.

#30 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#31 Add pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 4. to release, automated

#34 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#33 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#35 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#36 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/openapi.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, dependencies, automated

#39 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
